version: "3"

services:
  nginx:
    image: course_nginx:ver_1
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile_build
    ports: 
      - 80:80

  apache:
    image: course_apache:ver_1
    build: 
      context: .
      dockerfile: ./docker/apache/Dockerfile_build
    ports: 
      - 88:80

  php:
    image: course_php:ver_1
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile_build      