version: "3"

services:
  nginx:
    image: nginx:1.14.0
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/app/web  

  apache: 
    image: httpd
    ports:
      - 88:80
    volumes:
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./web:/var/www/app/web  

  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    user: "1000:1000"

  redis:
    image: redis:4.0.9
    volumes:
      - redis-data:/data
    command: '--appendonly yes'

  mongo:
    image: mongo:3.6.3
    volumes:
      - mongo-data:/data/db

  postgres: 
    image: postgres:10.12    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes: 
      - pg-data:/var/lib/postgresql/data

  mysql: 
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db
    volumes: 
      - mysql-data:/var/lib/mysql

volumes: 
  redis-data:
  mongo-data:  
  pg-data:
  mysql-data: