version: "3"

services:
  nginx:
    image: polinkot/docker-course:nginx
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile_build
    ports: 
      - 80:80

  apache:
    image: polinkot/docker-course:apache
    build: 
      context: .
      dockerfile: ./docker/apache/Dockerfile_build
    ports: 
      - 88:80

  php:
    image: polinkot/docker-course:php
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile_build      